### ISSUE TITLE
ACL Question - Probably wrong place

### ISSUE THREAD

**Issue by grivers3** [hassio-addons/addon-mqtt#16]
Thanks for the acl update.

Is there a way to configure reading some topics and writing others.
Other than this (this works):

>     {
>       "username": "test",
>       "password": "test",
>       "readonly": false,
>       "topics": [
>         "home/test/state/#"
>       ]
>     },
>     {
>       "username": "test",
>       "password": "test",
>       "readonly": true,
>       "topics": [
>         "home/test/command/#"
>       ]
>     }

**Comment by ludeeus** [comment]
With the simple configuration you can do there it's not possible other than the way you are showing here, and I do not see a clean way of doing this _not sure how many would need it_ 🤷‍♂️

**Comment by ludeeus** [comment]
Another way you can do this is by using a custom configuration.
<https://github.com/hassio-addons/addon-mqtt#custom-configuration>
