### ISSUE TITLE
Allow certificates to be in subfolders of /ssl/

### ISSUE THREAD

**Issue by penenkel** [hassio-addons/addon-mqtt#19]
# Problem/Motivation
I would like to place my certificates in a subfolder of /ssl/ and specifying a corresponding (relative) path in the options. 

## Actual behavior

Unfortunatly this is not supported. `40-nginx.sh` fails with a `sed` error. My interpretation is that the sed command used to fill the config template cannot handle the slashes in a path.

## Steps to reproduce

Simply specify a relative path instead of a filename in the options (and activate ssl of cause) and restart the addon. (To reproduce this you don't actually have to place a certfile at the specified location, as it will fail long before it would be used.) 

## Proposed changes
The error is caused by the following line in `mqtt/rootfs/etc/cont-init.d/40-nginx.sh`:
`sed -i "s/%%certfile%%/${certfile}/g" /etc/nginx/nginx-ssl.conf`

which modifies the followinf line in the config template `mqtt/rootfs/etc/nginx/nginx-ssl.conf`:
`ssl_certificate /ssl/%%certfile%%;`

As you can see specifiing a path relative to /ssl/ should work, at least from the perspective of the config file. Only the templating via sed fails. I'm hoping there is a relativly easy fix by modifing the sed statement.

**Comment by frenck** [comment]
I would strongly advise against it.
First of all, it is documented.
Secondly, Hass.io is going to change the way it handles certificates soon. We should be careful not to make changes that become incompatible.

**Comment by ludeeus** [comment]
I will follow @frenck's advise and not change the current options to allow this.
This should and will be handled by hassio in the future.
As a workaround untill then you can create symlinks for the certs so they are in `/ssl/`
