### ISSUE TITLE
Cannot configure Username/password for HiveMQ client

### ISSUE THREAD

**Issue by bennydiamond** [hassio-addons/addon-mqtt#22]
Install instructions contains no information on how to set the desired username and password for the HiveMQ web client part of this addon.

There is also no information on the default username and password for said web client.

Steps to reproduce:
* Install addon
* Go to Addon configuration page
* Read install documentation Readme
* There is no info on how to setup web client username and password

**Comment by timmo001** [comment]
If this is for the username and password that you are asked for when you load the web client, it's your Home Assistant credentials. If this is about MQTT users, the documentation for this is here:

https://github.com/hassio-addons/addon-mqtt#add-on-configuration-example

**Comment by ludeeus** [comment]
Answered by @timmo001, this is also in the README (Step 7) :)
```
7. Log in with your Home Assistant user.
```

**Comment by bfiset** [comment]
Missed that one sorry.

How can I change the default username/password?

**Comment by timmo001** [comment]
> Missed that one sorry.
> 
> How can I change the default username/password?

Add another user in Home Assistant
