### ISSUE TITLE
Anonymous access does not allow clients to publish

### ISSUE THREAD

**Issue by rutberg** [hassio-addons/addon-mqtt#23]
# Problem/Motivation

> I only use MQTT locally, and have a few units that can report to HA through MQTT and plan to expand that. I want to keep thigs as simple as possible, this not using any authentication for publishing and subscribing to MQTT.

## Expected behavior

> When enabling anonymous access I expect that a client can connect, subscribe to topics and publish topics without supplying a username or password.

## Actual behavior

> The only way I can get a client to publish on MQTT is to set a username and password and using that. If I don't submit user/password the client can connect and subscribe, but not publish.

## Steps to reproduce

> Enabling anonymous access, connecting with client not using password/username, publishing to a topic. Log yeilds: "DENIED publish from..."

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by ludeeus** [comment]
@rutberg Please share your current configuration for this addon.

**Comment by rutberg** [comment]
```
{
  "log_level": "debug",
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "web": {
    "enabled": true,
    "ssl": true
  },
  "broker": {
    "enabled": true,
    "enable_ws": true,
    "enable_mqtt": true,
    "enable_ws_ssl": true,
    "enable_mqtt_ssl": true,
    "allow_anonymous": true
  },
  "mqttusers": [
    {
      "username": "CantBeBlank",
      "password": "CantBeBlank",
      "readonly": false,
      "topics": [
        "#"
      ]
    }
  ]
}
```

**Comment by ludeeus** [comment]
If users are defined mosquitto will not allow anonymous access.
if you want to use `allow_anonymous`, you can't define any `mqttusers`
This can be done by setting that to this:

```
"mqttusers": []
```

**Comment by rutberg** [comment]
Thank you @ludeeus - that solved it.

In the beginning, I tried to test it by removing that omitting `mqttusers`

I.e.
```
{
  "log_level": "debug",
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "web": {
    "enabled": true,
    "ssl": true
  },
  "broker": {
    "enabled": true,
    "enable_ws": true,
    "enable_mqtt": true,
    "enable_ws_ssl": true,
    "enable_mqtt_ssl": true,
    "allow_anonymous": true
  }
}
```

But that didn't work, and leaving the fields blank didn't work either. Thanks for the help with showing the third option 👍
