### ISSUE TITLE
MQTT Light not read availability_topic on boot of HA

### ISSUE THREAD

**Issue by maxalbani** [hassio-addons/addon-mqtt#26]
# Problem/Motivation
availability_topic message not read on boot of HA, the mqtt light device show as unavaiable.
If I manually reboot these devices or re-send the availability message via MQTT everything works fine.

my config is:

`- platform: mqtt 
  name: "Terrazzo Salotto" 
  state_topic: "shellies/shelly1-55EED9/relay/0" 
  command_topic: "shellies/shelly1-55EED9/relay/0/command"
  availability_topic: "shellies/shelly1-55EED9/online" 
  qos: 0 
  payload_on: "on" 
  payload_off: "off" 
  payload_available: "true" 
  payload_not_available: "false" 
  optimistic: false 
  retain: false`

**Home Assistant release with the issue:**
0.87.1

**Last working Home Assistant release (if known):**
0.86.x

**Operating environment (Hass.io/Docker/Windows/etc.):**
Hass.io on RPi 3B

**Comment by maxalbani** [comment]
i'm sorry. i'm using addon Mosquitto Broker, this is an another addon, right?

**Comment by ludeeus** [comment]
Correct, this also looks like a Home Assistant issue.
