### ISSUE TITLE
MQTT Server not ready when HA trying to connect after a reboot

### ISSUE THREAD

**Issue by starwolf73** [hassio-addons/addon-mqtt#27]
# Problem/Motivation
Receiving this error every time after a host reboot: Error talking to MQTT: The client is not currently connected. This cause all MQTT entities to be in yellow and not available. 

If I do a HASS restart after a host reboot or power on, it work connect correctly.

Host:
VirtualBox -> VM 4 Cores - 4 GB RAM / SSD drive

## Expected behavior
HA should wait until MQTT service is up before connecting.

## Actual behavior
HA try to connect to the MQTT service when it is still loading. 

## Steps to reproduce
- Install MQTT Server Add-ons and configure it
Config:
```
{
  "log_level": "info",
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "web": {
    "enabled": true,
    "ssl": false
  },
  "broker": {
    "enabled": true,
    "enable_ws": true,
    "enable_mqtt": true,
    "enable_ws_ssl": false,
    "enable_mqtt_ssl": false,
    "allow_anonymous": true
  },
  "mqttusers": [
    {
      "username": "xxxxx",
      "password": "xxxxx",
      "readonly": false,
      "topics": [
        "#"
      ]
    }
  ]
}
```

**Configuration.yaml:**
```
# MQTT Connection
mqtt:
  broker: a0d7b954-mqtt
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home-assistant
```

- Setup some MQTT light in Configuration.yaml (example below)
```
# Milight Type: MQTT_JSON
  - name: "Office lamp"
    platform: mqtt
    schema: json
    #                                   ________________ Device ID
    #                                  |        ________ Device Type
    #                                  |       |     ___ Group ID
    #                                  |       |    |
    #                                  v       v    v
    command_topic: "milight/commands/0x72C6/rgb_cct/1"
    state_topic: "milight/states/0x72C6/rgb_cct/1"
    qos: 1
    optimistic: false
    retain: true
   
    #-- Bulb configuration
    brightness: true
    rgb: true
    color_temp: true

    # HA missing scale temp feature. On todo list...
    #color_temp_min: 0 
    #color_temp_max: 100
    
    # Milight GW command is "saturation", so white_value doesn't take effect. On todo list...
    # white_value: true 
    
    effect: true
    #Effect list 0=Full, 1=White, 2=RGB, 3=Full hard, 4=Disco, 5=Red Flash, 6=Green Flash, 7=Blue Flash, 8=White Flash]
    effect_list: [0, 1, 2, 3, 4 ,5, 6, 7, 8]
    #effect_speed: true # Milight hub support it. HA missing this feature. 
    
    # Transistion: Milight bulb doesn't support it :(. Need workaround to be done via software on HA or Milight GW)
    #transition: true
```
- Make sure your MQTT connection work and MQTT light is working fine.
- Reboot host
- Your MQTT light will appear all yellow with "Entity not available: xxx"

## Proposed changes

Based on the documentation of [MQTT](https://www.home-assistant.io/docs/mqtt/broker#configuration-variables) on Home Assistant, I suspect that the MQTT Addon is missing the following:

> If you are running a Mosquitto instance on the same server as Home Assistant then you must ensure that the Mosquitto service starts before Home Assistant. For a Linux instance running Systemd (Raspberry Pi, Debian, Ubuntu and others) then you should edit the file /etc/systemd/system/home-assistant@homeassistant.service as root (e.g., sudo nano /etc/systemd/system/home-assistant@homeassistant.service) and add the Mosquitto service: [Unit] Description=Home Assistant After=network.target mosquitto.service

**Comment by ludeeus** [comment]
> HA should wait until MQTT service is up before connecting.

I agree, but that has to change in the code in Home Assistant.
_This addon starts before HA, but it uses a longer time to start_

**Comment by starwolf73** [comment]
I don’t understand why this is closed since It is a CRITICAL bug for this addon and this bug is only relate to this addon. I believe every addon should be able to register them self to HA service file. Can you please let it open until it is fixed ?

**Comment by pergolafabio** [comment]
i encounter the same thing, but if i do a complete reboot of my hassos, then i know i just need to restart HA after it
so whats the big deal? :)
the only issue is, if you have a power interrupt , that you dont know ... then mqtt is indeed an issue

**Comment by pergolafabio** [comment]
but i think you need to make an issue bug report on HA instead of here 

if you create one, pls let me know , so i can subscribe :)

**Comment by ludeeus** [comment]
@starwolf73 This was closed since the issue here is with Home Assistant and not the addon itself, Home Assistant should try to connect on startup if it fails it should wait for x seconds and try again.

There _is_ a setting I can tweak in the configuration to make the addon start even earlier, but that did not always work during my testing, and it also made the whole system slower in startup times.

You will only experience this if you reboot the host something that should occur rarely.
When you **have to** _reboot_ the host, the workaround described by @pergolafabio are a good option.

**Comment by vajonam** [comment]
this seems to happen more often now, my hassio supervisor is restarting HA and MQTT not sure why.. or how.. but once in a couple of days I see that the all the MQTT senors are longer work and the MQTT server is also not up.. I will attach the log once I see this again. It happens on 4.1 and 4.0

**Comment by starwolf73** [comment]
All, I just post the same issue as suggest to HA site. 
https://github.com/home-assistant/home-assistant/issues/22146

**Comment by vajonam** [comment]
I will post a log file from the mqtt add restart failure as well. both the issues are related. HA should retry but the fact the mqtt addon doesn't restart when hassio_supervisor restart is a problem as well Once I have the logs I will reopen the issue
