### ISSUE TITLE
FATAL: The configured certfile is not found

### ISSUE THREAD

**Issue by Repair-Lab** [hassio-addons/addon-mqtt#29]
I´m trying to lern MQTT and have Homeassistant with respi3+

Now try update from normal to this addon ......
have changed all to see in manual but it not runs and says this.

`armhf / HassOS 1.13 / HA 0.87.1 / SU 143 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
FATAL: The configured certfile is not found  <<<<why? everything is normal
[cont-init.d] 10-requirements.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
`

im try and make all to false : 

{
  "log_level": "info",
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "web": {
    "enabled": true,
    "ssl": false
  },
  "broker": {
    "enabled": true,
    "enable_ws": false,
    "enable_mqtt": false,
    "enable_ws_ssl": false,
    "enable_mqtt_ssl": false,
    "allow_anonymous": false
  },
  "mqttusers": [
    {
      "username": "hassio",
      "password": "ha",
      "readonly": true,
      "topics": [
        "#"
      ]
    }
  ]
}
this works not realy and can not enter the website. >>SSL_ERROR_RX_RECORD_TOO_LONG <<
and have this on my log.
  first beginns normal after minute this here :-/

`1550503846: New client connected from 192.168.188.25 as DVES_0F45CE (c1, k10, u'hassio').
1550503847: New connection from 192.168.188.23 on port 1883.
1550503847: New client connected from 192.168.188.23 as DVES_17F25D (c1, k10, u'hassio').
2019/02/18 16:32:57 [info] 920#920: *1 client sent invalid method while reading client request line, client: 192.168.188.26, server: _, request: "����V)_��y㨡�tܠ�bش��S"
192.168.188.26 - - [18/Feb/2019:16:32:57 +0100] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03\xF1\xC2\x9FV)\x05_\xA9\xBEy\xE3\xA8\xA1\x92t\xDC\xA0\x99b\xD8\xB4\x18\xE8\x7F\xA8S" 400 173 "-" "-"
2019/02/18 16:33:00 [info] 920#920: *2 client sent invalid method while reading client request line, client: 192.168.188.26, server: _, request: "������8�¨����~K�&�+�<8��R�Xڔ4 X���J�-H�t�d�r�Q�ře��\���(\{�$�+�/̨̩�,�0�"
192.168.188.26 - - [18/Feb/2019:16:33:00 +0100] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03\xFE\xB6\xB58\x8D\xC2\xA8\xB1\x8A\x1B\xC3\xEB~K\xA5&\xE8+\xB4<8\xD4\xCCR\x0B\x9AX\x06\xDA\x944\x1F X\x0E\xC3\xFB\x88J\xF2\xA3-H\x0B\xF6t\xBFd\x8Ar\x9DQ\x8D\xC5\x99e\xB7\xC2\x5C\xB4\xBA\x94(\x5C{\x00$\x13\x01\x13\x03\x13\x02\xC0+\xC0/\xCC\xA9\xCC\xA8\xC0,\xC00\xC0" 400 173 "-" "-"`

what can i do???  sorry for my bad english.........

**Comment by ddnut** [comment]
`cd /etc/ssl && touch privkey.pem && touch fullchain.pem`

just needs to find the files I found it dont use them

**Comment by ludeeus** [comment]
```
this works not realy and can not enter the website. >>SSL_ERROR_RX_RECORD_TOO_LONG <<
```
remove the `s` in https from the url after you click "OPEN WEBUI"

**Comment by Btje1977** [comment]
removing the s wont's work. Got the same error.

**Comment by ludeeus** [comment]
If you do open another issue and fill out the template @Btje1977

**Comment by vikdb** [comment]
Got the same error.. No fix?

**Comment by Btje1977** [comment]
Reboot solved it.

Op vr 15 mrt. 2019 om 11:39 schreef vikdb <notifications@github.com>:
