### ISSUE TITLE
Access control list

### ISSUE THREAD

**Issue by frenck** [hassio-addons/addon-mqtt#3]
# Motivation

In case #2 gets implemented, it would be great to be able to control the permissions per user.
Mosquitto allows for limiting users to specific topics including read, write and readwrite permissions.

Adding this would give major security controls.

**Comment by ludeeus** [comment]
Thanks for suggesting this, ACL support was added in https://github.com/hassio-addons/addon-mqtt/commit/abb57d9a2379b04cc2bb8cabe4ce34a57af37c22
