### ISSUE TITLE
Unable to limit logs

### ISSUE THREAD

**Issue by sickidolderivative** [hassio-addons/addon-mqtt#30]
# Problem/Motivation

I want to limit the amount of messages in mosquitto addon logs. I have a simple mqtt client that reconnects every second to read and/or post. That results in excessive logs.

I run Home Assistant 0.87.0 on HassOS 2.8.

My addon setup is the following:
{
  "logins": [],
  "anonymous": false,
  "customize": {
    "active": true,
    "folder": "mosquitto"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}

Content of /share/mosquitto/mosquitto.conf file is the following:
log_type none
connection_messages false
log_dest none

## Expected behavior

I hoped to eliminate login messages in the addon logs.

## Actual behavior

I get multiple [INFO] messages on every login:

[INFO] found mqtt on Home Assistant
[INFO] found mqtt on Home Assistant
[INFO] found mqtt on Home Assistant
[INFO] found mqtt on Home Assistant

mqtt is the username in HA used for login by mosquitto client.

**Comment by ludeeus** [comment]
Hi
You are using the core mosquitto addon, you should open an issue there :)
https://github.com/home-assistant/hassio-addons
