### ISSUE TITLE
No OCSP responder URL in the certificate

### ISSUE THREAD

**Issue by ericdes** [hassio-addons/addon-mqtt#35]
Hello,

I'm trying your addon with a self-signed certificate and I'm getting this in the logs:

nginx: [warn] "ssl_stapling" ignored, no OCSP responder URL in the certificate "/ssl/my_selft_signed_certificate.pem"

Would it be possible to by-pass that OSCP check?

Thank you!

**Comment by frenck** [comment]
It is a warning that doesn’t effect the working. What is your question?

**Comment by ericdes** [comment]
Yes, I noticed that I wasn’t affecting the working a bit later. Other than that, everything’s fine.

 

Thank you!

**Comment by frenck** [comment]
Check! Thanks for letting us know! 👍
