### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by ericdes** [hassio-addons/addon-mqtt#36]
Hello,

I'm getting this error in the logs when trying to connect a device at 10.0.6.28 via MQTT SSL:

1553966506: Client connection from 10.0.6.28 failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number.

Would you know what the problem is?

Thank you!

**Comment by ludeeus** [comment]
Looks like there is a mismatch with the SSL version on the client and the server, is your client using an old lib to connect?

**Comment by ericdes** [comment]
I’m using the Tasmota firmware on the client — actually on most of my devices.

**Comment by ludeeus** [comment]
Just tested the latest version, no issues with using SSL.
Jump on to discord or the forums if you need help troubleshooting your issue.
