### ISSUE TITLE
(re-opening) Anonymous  access not allow to publish

### ISSUE THREAD

**Issue by mnefk** [hassio-addons/addon-mqtt#38]
# Version

> Add-on version: 1.0.1
> You are running the latest version of this add-on.
> System: HassOS 2.11  (amd64 / qemux86-64)
> Home Assistant version: 0.91.4
> Supervisor version: 160

# Problem

As i wrote with you in discord, the client cant publish, its denied but i configured it as "anonymous"

> 1555962674:New connection from 192.168.0.115 on port 1883.
> 1555962674: New client connected from 192.168.0.115 as DHT_Pub (c1, k60).
> 1555962674: No will message specified.
> 1555962674: Sending CONNACK to DHT_Pub (0, 0)
> 1555962674: Denied PUBLISH from DHT_Pub (d0, q0, r0, m0, 'mirror/temperature1', ... (13 bytes))
> 1555962674: Denied PUBLISH from DHT_Pub (d0, q0, r0, m0, 'mirror/humidity1', ... (4 bytes))
> 1555962674: Received DISCONNECT from DHT_Pub
> 1555962674: Client DHT_Pub disconnected.

## Configuration

> {
  "log_level": "info",
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "web": {
    "enabled": false,
    "ssl": true
  },
  "broker": {
    "enabled": true,
    "enable_ws": false,
    "enable_mqtt": true,
    "enable_ws_ssl": false,
    "enable_mqtt_ssl": false,
    "allow_anonymous": true
  },
  "mqttusers": []
}

## Related to this issue

https://github.com/hassio-addons/addon-mqtt/issues/23

**Comment by rbhr** [comment]
My config is exactly the same and I can verify that publish is denied for anonymous users.

**Comment by ludeeus** [comment]
This has been corrected in the newest version of this addon.
