### ISSUE TITLE
mqtt

### ISSUE THREAD

**Issue by serwan19** [hassio-addons/addon-mqtt#49]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
empty issue, closing it.

**Comment by serwan19** [comment]
aplikationsmqtt
