### ISSUE TITLE
s6-maximumtime: warning: child process crashed

### ISSUE THREAD

**Issue by shajek** [hassio-addons/addon-mqtt#50]
## Expected behavior

start addon

## Actual behavior

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[cont-init.d] 00-banner.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
s6-maximumtime: warning: child process crashed
[cont-finish.d] 99-message.sh: exited 111.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

## Steps to reproduce

Latest HassOS 2.12 on RPI Zero W and MQTT Server & Web client 1.1.0

**Comment by sinclairpaul** [comment]
Sorry to say it, but "RPI Zero W" is really best efforts.
