### ISSUE TITLE
Bind is failing, MQTT can't start

### ISSUE THREAD

**Issue by jwhite** [hassio-addons/addon-mqtt#54]
I thought I had this working so it might be a hass update broke it?

I'm getting 

20-01-26 18:14:32 ERROR (SyncWorker_3) [hassio.docker] Can't start addon_a0d7b954_mqtt: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_a0d7b954_mqtt (7fdc5036843c32613b8ef7819060aa0446209615f37d0b1aee69298557bead4f): Bind for 0.0.0.0:1884 failed: port is already allocated")

My hass configuration.yaml looks like this :

mqtt:
    broker: a0d7b954-mqtt
    username: !secret mqtt_username
    password: !secret mqtt_password
    client_id: home-assistant

    discovery: true
    discovery_prefix: homeassistant

Where secrets are correctly defined.

I'm not sure what is taking the port.

**Comment by sinclairpaul** [comment]
Do you have the official Mosquitto Broker addon installed?

Something is already listening on 1884.

**Comment by jwhite** [comment]
Yes, I did.  Thanks.  Thought changing the MQTT entry took care of that.
