### ISSUE TITLE
deprecated

### ISSUE THREAD

**Issue by fonta** [hassio-addons/addon-mqtt#55]
The official addon doesn't have the hivemq webclient.
In stead of removing the add-on, could you maybe only remove the mqtt broker part?

**Comment by frenck** [comment]
Nope, the webclient causes quick a few issues and it one of the reasons to deprecate the add-on in the first place.

Other options are: The now builtin available MQTT tools inside the Home Assistant developers tab, MQTTExplorer and the CLI tools available in the SSH & VSCode add-ons.
