### ISSUE TITLE
Connect failed: AMQJS0007E Socket error:undefined.

### ISSUE THREAD

**Issue by klikodes** [hassio-addons/addon-mqtt#56]
# Problem/Motivation

I intall MQTTServer&web client and when i try to connet using HiveMQ I get error: "Connect failed: AMQJS0007E Socket error:undefined."

![image](https://user-images.githubusercontent.com/45907348/76169643-9d3ac400-617a-11ea-9498-4bf9f00e30a0.png)

Log ouput is:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: MQTT Server & Web client
 Mosquitto MQTT Server bundled with Hivemq's web client
-----------------------------------------------------------
 Add-on version: 1.2.0
 You are running the latest version of this add-on.
 System: HassOS 3.11  (armv7 / raspberrypi4)
 Home Assistant Core: 0.106.4
 Home Assistant Supervisor: 207
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] hivemq.sh: executing... 
patching file /app/index.html
[cont-init.d] hivemq.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[18:37:41] INFO: Adding configuration for MQTT Server...
[18:37:42] INFO: Setting up user esfacilhacerlo
[18:37:42] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:37:44] INFO: Starting mosquitto MQTT Server...
1583692664: mosquitto version 1.6.4 starting
1583692664: Config loaded from /opt/mosquitto.conf.
1583692664: Opening ipv4 listen socket on port 1883.
1583692664: Opening ipv6 listen socket on port 1883.
1583692664: Opening websockets listen socket on port 1884.
[18:37:44] INFO: Starting NGINX for the MQTT client...
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
1583692670: New connection from 172.30.32.1 on port 1883.
1583692670: New client connected from 172.30.32.1 as servidorlocal (p2, c1, k60, u'esfacilhacerlo').
[08/Mar/2020:18:53:11 +0000] 200 192.168.0.25, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36)
[08/Mar/2020:18:53:11 +0000] 200 192.168.0.25, 172.30.32.1(172.30.32.2) GET /config.js HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36)
1583694464: Saving in-memory database to /data/mosquitto/mosquitto.db.
[08/Mar/2020:19:18:23 +0000] 304 192.168.0.25, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36)
[08/Mar/2020:19:18:23 +0000] 304 192.168.0.25, 172.30.32.1(172.30.32.2) GET /config.js HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36)

Configuration in MQTT Server & Web client is:

ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
broker: true
allow_anonymous: false
mqttusers:
  - username: esfacilhacerlo
    password: esfacilhacerlo
    readonly: true
    topics:
      - '#'

And configuration.yaml:

mqtt:
  broker: localhost
  client_id: servidorlocal
  username: esfacilhacerlo
  password: esfacilhacerlo

There are other issues about this error message but they are close with not solution.

Thanks,

<blockquote><img src="https://avatars0.githubusercontent.com/u/7390180?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/openresty/luajit2">openresty/luajit2</a></strong></div><div>OpenResty's Branch of LuaJIT 2. Contribute to openresty/luajit2 development by creating an account on GitHub.</div></blockquote>
<blockquote><div><strong><a href="https://openresty.org/en/download.html">OpenResty - Download</a></strong></div></blockquote>

**Comment by frenck** [comment]
`homeassistant` is not valid. You need to use your hostname.

Furthermore, this add-on is deprecated. Please migrate away from it.
