### ISSUE TITLE
Global self signed SSL certificates from Raspberry

### ISSUE THREAD

**Issue by SaschaMuehl** [hassio-addons/addon-mqtt#57]
# Problem/Motivation
I want to integrate my self flashed CC2531 via MQTT. After the Installation of the MQTT Server & Web client I tried to integrate my self signed certificates of letsencrypt. 

I use a LEMP-Stack on a Rasp-Pi 3 (32bit) with a SPDNS.org DNS Server and installed HassIO on Docker. The LEMP is running globally with:
Debian, NGINX Reverse Proxy, RSA LetsEncrypt Certificates, MariaDB-Database, PHP 7.0

## Expected behavior
Access to the SSL MQTT Server via SSL

## Actual behavior
Connect failed: AMQJS0007E Socket error:undefined.
The way without certificates were also not working - It is not connecting after clicking

## Steps to reproduce
Prolog: First of all I tríed to integrate the Zigbee2MQTT for CC2531 iaw. [zigbee2mqtt.io](https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html) documenation. I stopped it because I got a "Connecting to MQTT server at mqtt://127.0.0.1:1883" error. So I tried to use the mqtt-addon

configuration.yaml:
![grafik](https://user-images.githubusercontent.com/62723171/79908793-26047b00-841c-11ea-8db5-8eefc57bf9db.png)

Add-On-Config
![grafik](https://user-images.githubusercontent.com/62723171/79907999-cce81780-841a-11ea-84be-53ce28ea1811.png)

Network-Config
![grafik](https://user-images.githubusercontent.com/62723171/79907538-053b2600-841a-11ea-8146-2c23d31ed6d6.png)

1. Is there a way to bind the self signed SSL certificates? 
2. Were can I find the wanted file SSL? (I want to avoid a constant changing of the SSL Certs)

**Comment by frenck** [comment]
This add-on has been deprecated. Please migrate away from it and use the official Mosquitto add-on instead.

Thanks 👍
