### ISSUE TITLE
Web client socket error

### ISSUE THREAD

**Issue by nnmalex** [hassio-addons/addon-mqtt#6]
# Problem/Motivation

Trying to connect to the server via the web-interface I get an error "Connect failed: AMQJS0007E Socket error:undefined."

## Steps to reproduce

Freash install. MQTT broker works and I can see devices connecting to it in logs.

**Comment by frenck** [comment]
Please provide more details on your settings and setup.
This is most likely just a configuration/settings error.

**Comment by nnmalex** [comment]
Sure. I have a Hass.io running in Docker on a Debian machine.

My config is:

{
  "log_level": "info",
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "web": {
    "enabled": true,
    "username": "username",
    "password": "password",
    "ssl": false
  },
  "broker": {
    "enabled": true,
    "enable_ws": true,
    "enable_mqtt": true,
    "enable_ws_ssl": false,
    "enable_mqtt_ssl": false,
    "allow_anonymous": false
  },
  "mqttusers": [
    {
      "username": "mqttuser",
      "password": "mqttpassword",
      "readonly": false,
      "topics": [
        "#"
      ]
    }
  ]
}

**Comment by ludeeus** [comment]
Can you post a screenshot with what you are trying to use to connect?

**Comment by nnmalex** [comment]
I've tried again now and was able to connect. Didn't change anything since reporting the issue.
