### ISSUE TITLE
Connecting to CloudMQTT as a MQTT bridge

### ISSUE THREAD

**Issue by e2m32** [hassio-addons/addon-mqtt#9]
# Problem/Motivation

Looking to move over from Official MQTT server for the WebUI for debugging

--
Is there a way to configure an MQTT bridge to say cloud mqtt? I've accomplished this with the offical MQTT server using this setup: https://community.home-assistant.io/t/solved-mqtt-over-internet-aka-how-to-set-up-cloudmqtt-bridge-with-hassio-mosquitto-broker/49939/8

Does this still exist for this add on as well?

<blockquote><img src="https://community.home-assistant.io/user_avatar/community.home-assistant.io/krash/200/20614_1.png" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/solved-mqtt-over-internet-aka-how-to-set-up-cloudmqtt-bridge-with-hassio-mosquitto-broker/49939/8">[solved] Mqtt over internet? aka: "How to set up cloudMQTT bridge with Hassio mosquitto broker"</a></strong></div><div>I have not worked with NodeRed at all, but i figured it out without it.  Here is how i did it, by compiling info from all around the community forums:   Register CloudMQTT free account. Ignore the initial un/pw and create two (in my case) new users with their own passwords. In the users page of cloudMQTT, scroll down after creating the users and click topic, select the user, add # (in case you want them in on everything) in the pattern box, then tick read/write access accordingly and add them tw...</div></blockquote>

**Comment by ludeeus** [comment]
Currently no, but I will check out the posibilities

**Comment by pjv** [comment]
wait, you mean if i configure a bridge to an external mqtt in the "custom configuration" in the `/config/mqtt` directory (per the add-on's documentation) that it won't work?

**Comment by pjv** [comment]
ok, assuming from looking at your commits in here that the documentation on the readme is ahead of the functionality of the latest release (that i am running on my HA), is there an easy way for me to upgrade my hass.io install of the add-on to the HEAD of this repo so i can get this functionality now? Or do i need to wait for you to push a new release? And if so, how long do you think that will be?

**Comment by pjv** [comment]
@ludeeus thanks for clarifying. 

FYI, i installed the add-on this morning and was linked from within the add-on to the documentation on the master branch which obviously includes this new, un-released, custom config capability. based on the documentation i read, i had configured a bridge to an external MQTT instance and spent a couple hours trying to debug why it wasn't working. Maybe in the future it would be better for the released add-on to link to the documentation for the release tag (i.e. the link you just showed me above) rather than the master branch.

**Comment by ludeeus** [comment]
I agree with that, will take it into consideration for future releases.

**Comment by ludeeus** [comment]
This should now be possible in v0.2.0
